language: go
go:
  - 1.14.4

sudo: required

services:
  - docker

script:
  - go test -v ./...

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make docker-build && make docker-push ;
    fi;