language: go
go:
  - 1.15.1

# set the version for petze during build
# bump the version ident here
env:
  - VERSION=v1.0.1

sudo: required

services:
  - docker

script:
  - go test -v ./...

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      TAG=${VERSION} make docker-build && make docker-push ;
    fi;